#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cumulus-nclu-nc-1.0.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cumulus-nclu-nc-1.0.yang


class ns(object):
    hash = 894775464

    id = "http://tail-f.com/ns/ned-id/cumulus-nclu-nc-1.0"

    uri = "http://tail-f.com/ns/ned-id/cumulus-nclu-nc-1.0"

    prefix = "cumulus-nclu-nc-1.0"

    cumulus_nclu_nc_10x2e0_cumulus_nclu_nc_10x2e0 = 1999849485
    cumulus_nclu_nc_10x2e0_cumulus_nclu_nc_10x2e0_ = "cumulus-nclu-nc-1.0"
