#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/cumulus-nclu.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module cumulus-nclu.yang


class ns(object):
    hash = 2046954570

    id = "_cumulus-nclu-nc-1.0:cumulus-nclu-nc-1.0#http://example.com/cumulus-nclu"

    uri = "_cumulus-nclu-nc-1.0:cumulus-nclu-nc-1.0#http://example.com/cumulus-nclu"

    prefix = "cumulus"

    cumulus_commands = 913421552
    cumulus_commands_ = "commands"
    cumulus_cmd = 522674463
    cumulus_cmd_ = "cmd"
