#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cumulus-nclu-nc.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cumulus-nclu-nc.yang


class ns(object):
    hash = 776827634

    id = "http://tail-f.com/ns/ned-id/cumulus-nclu-nc"

    uri = "http://tail-f.com/ns/ned-id/cumulus-nclu-nc"

    prefix = "cumulus-nclu-nc"

    cumulus_nclu_nc_cumulus_nclu_nc = 1152583159
    cumulus_nclu_nc_cumulus_nclu_nc_ = "cumulus-nclu-nc"
    ned_id = 1152583159
    ned_id_ = "cumulus-nclu-nc:cumulus-nclu-nc"
