/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/cumulus-nclu.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cumulusnclu.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module cumulus-nclu.yang */
public class cumulusNclu extends ConfNamespace {
    public static final int hash = 2046954570;
    public int hash() {
        return cumulusNclu.hash;
    }

    public static final String id = "_cumulus-nclu-nc-1.0:cumulus-nclu-nc-1.0#http://example.com/cumulus-nclu";
    public String id() {
        return cumulusNclu.id;
    }

    public static final String uri = "_cumulus-nclu-nc-1.0:cumulus-nclu-nc-1.0#http://example.com/cumulus-nclu";
    public String uri() {
        return cumulusNclu.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(cumulusNclu.uri);
    }

    public static final String prefix = "cumulus";
    public String prefix() {
        return cumulusNclu.prefix;
    }

    public cumulusNclu() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _commands = 913421552;
    public static final String _commands_ = "commands";
    public static final int    _cmd = 522674463;
    public static final String _cmd_ = "cmd";
}
