/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cumulus-nclu-nc-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cumulusnclu.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cumulus-nclu-nc-1.0.yang */
public class tailfNedIdCumulusNcluNc1_0 extends ConfNamespace {
    public static final int hash = 894775464;
    public int hash() {
        return tailfNedIdCumulusNcluNc1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cumulus-nclu-nc-1.0";
    public String id() {
        return tailfNedIdCumulusNcluNc1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cumulus-nclu-nc-1.0";
    public String uri() {
        return tailfNedIdCumulusNcluNc1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCumulusNcluNc1_0.uri);
    }

    public static final String prefix = "cumulus-nclu-nc-1.0";
    public String prefix() {
        return tailfNedIdCumulusNcluNc1_0.prefix;
    }

    public tailfNedIdCumulusNcluNc1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cumulus_nclu_nc_10x2e0 = 1999849485;
    public static final String _cumulus_nclu_nc_10x2e0_ = "cumulus-nclu-nc-1.0";
}
