/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cumulus-nclu-nc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cumulusnclu.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cumulus-nclu-nc.yang */
public class tailfNedIdCumulusNcluNc extends ConfNamespace {
    public static final int hash = 776827634;
    public int hash() {
        return tailfNedIdCumulusNcluNc.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cumulus-nclu-nc";
    public String id() {
        return tailfNedIdCumulusNcluNc.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cumulus-nclu-nc";
    public String uri() {
        return tailfNedIdCumulusNcluNc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCumulusNcluNc.uri);
    }

    public static final String prefix = "cumulus-nclu-nc";
    public String prefix() {
        return tailfNedIdCumulusNcluNc.prefix;
    }

    public tailfNedIdCumulusNcluNc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cumulus_nclu_nc = 1152583159;
    public static final String _cumulus_nclu_nc_ = "cumulus-nclu-nc";
    public static final int    ned_id = 1152583159;
    public static final String ned_id_ = "cumulus-nclu-nc:cumulus-nclu-nc";
}
